config/routes.rb
Rails.application.routes.draw do
  root 'courses#index'
  get 'courses/new', to: 'courses#new'
  get 'about', to: 'pages#about'
  resources :students
 
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/course.rb
class Course < ApplicationRecord
  validates :name, presence: true, length: {minimum: 5, maximum: 50}
  validates :short_name, presence: true, length: {minimum: 3, maximum: 15}
  validates :description, presence: true, length: {minimum: 10, maximum: 300}
end

app/models/student.rb
class Student < ApplicationRecord
  before_save { self.email = email.downcase }
  validates :name, presence: true, length: {minimum: 5, maximum: 50}
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i   
  validates :email, presence: true,
                        uniqueness: { case_sensitive: false }, 
                        length: { maximum: 105 },
                        format: { with: VALID_EMAIL_REGEX }  
  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController

  def index
    @courses = Course.all
  end

  def new

  end
  
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def about

  end

end

app/controllers/students_controller.rb
class StudentsController < ApplicationController

    before_action :set_student, only: [:show, :edit, :update]

    def index
      @students= Student.all
    end
  
    def show

    end

    def new
      @student= Student.new
    end
    
    def create
      @student= Student.new(student_params)  
      if @student.save
        flash[:success] = "You have successfully signed up"
        redirect_to @student
      else
        render 'new'       
      end
    end

    def edit

    end

    def update

      if @student.update(student_params)
        flash[:notice]= "You have successfully updated yout profile"
        redirect_to student_path(@student)
      else
        render 'edit'
      end  
    end

   private

  def set_student
    @student= Student.find(params[:id])
  end

    def student_params
      params.require(:student).permit(:name, :email)
    end
     
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/courses/index.html.erb
<h1> This is home page </h1>

app/views/courses/new.html.erb
<h1> This is a new course page </h1>

app/views/layouts/_footer.html.erb
<footer class="page-foote purple accent-3">
          <div class="container">
            <div class="row">
              <div class="col l6 s12">
                <h5 class="white-text">University</h5>
                <p class="grey-text text-lighten-4">The future of development training</p>
              </div>
              <div class="col l4 offset-l2 s12">
                <h5 class="white-text">Information</h5>
                <ul>
                  <li><a class="grey-text text-lighten-3" href="#!">Help</a></li>
                  <li><a class="grey-text text-lighten-3" href="#!">About</a></li>
                  <li><a class="grey-text text-lighten-3" href="#!">Contact us</a></li>
                </ul>
              </div>
            </div>
          </div>
          <div class="footer-copyright">
            <div class="container ">
              <span class="white-text text-darken-2">© 2022 University</span>
              <a class="grey-text text-lighten-4 right" href="#!">About</a>
            </div>
          </div>
</footer>

app/views/layouts/_navigation.html.erb
  <header>
    <ul id="dropdown1" class="dropdown-content ">
      <li><a href="#!">one</a></li>
      <li><a href="#!">two</a></li>
      <li class="divider"></li>
      <li><a href="#!">three</a></li>
    </ul>
    <ul id="dropdown2" class="dropdown-content">
      <li><a href="#!">one</a></li>
      <li><a href="#!">two</a></li>
      <li class="divider"></li>
      <li><a href="#!">three</a></li>
    </ul>
      <nav class ="purple accent-3">
        <div class="container">
          <div class="nav-wrapper">
            <a href="#" class="brand-logo right">University</a>
            <a href="#" data-target="mobile-demo" class="sidenav-trigger"><i class="material-icons">menu</i></a>
            <ul id="nav-mobile" class="left hide-on-med-and-down">
              <li><a href="sass.html">Courses</a></li>
              <li><a href="badges.html">Enrollments</a></li>
              <li><a class="dropdown-trigger" href="#!" data-target="dropdown1">Account<i class="material-icons right">arrow_drop_down</i></a></li>
            </ul>
             <ul class="sidenav" id="mobile-demo">
               <li><a href="sass.html">Courses</a></li>
               <li><a href="badges.html">Enrollments</a></li>
               <li><a class="dropdown-trigger" href="#!" data-target="dropdown2">Account<i class="material-icons right">arrow_drop_down</i></a></li>
             </ul>
          </div>
        </div>
      </nav>
      <% flash.each do |key, message| %>
        <div class="container">
          <div class="row sign-up-form">
            <div class="col s12 m12">
              <div class="card-panel red lighten-2" id="fade-out-target">
                <span class="white-text">
                  <%= message %>
                </span>
              </div>
            </div>
          </div>
        </div>
      <% end %>
    </header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>UnivApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navigation' %>
    <main>
      <div class="container">
        <%= yield %>
      </div>
    </main>
    <%= render 'layouts/footer'%>
  </body>
</html>

app/views/pages/about.html.erb
<h1> This is about page </h1>

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
  <div class="container">
    <div class="row sign-up-form">
      <div class="col s12 m12">
        <div class="card-panel red lighten-2 ">
          <span class="white-text">
            <strong><%= pluralize(obj.errors.count, "error") %></strong>
            prohibited your profile from being created
            <ul>
              <% obj.errors.full_messages.each do |message| %>
                <li><%= message %></li>
              <% end %>
            </ul>
          </span>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/students/_form.html.erb
<%= render 'shared/errors', obj: @student %>

<div class="container">
  <div class="row center sign-up-form">
    <div class="col s12 m12 l12">
      <div class="card-panel">
        <h3><%= @student.new_record? ? "Sign up" : "Edit your profile" %></h3>
        <div class="row">      
          <%= form_for(@student, html: {class: "col s12"}) do |f| %>
            <div class="row">
              <div class="input-field col s12">
                <%= f.text_field :name, placeholder: "Enter yout full name", autofocus: true %>
                <%= f.label :name %>
              </div>
            </div> 
            <div class="row">
              <div class="input-field col s12">
                <%= f.label :email %>
                <%= f.email_field :email %>
              </div>
            </div>
            <div class="row">
              <div class="input-field col s12">
                <%= f.submit(@student.new_record? ? "Sign up" : "Submit updates", class: "btn waves-effect waves-light right") %>
              </div>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/students/edit.html.erb
<%= render 'form' %>

app/views/students/index.html.erb
<div class="row">
  <div class="col s12">
    <h3 class="center-align">Students Listing</h3>
  </div>
</div>

<div class="row">
    <% @students.each do |student| %>
      <div class="col s6 m6">
        <div class="card blue-grey darken-1">
          <div class="card-content white-text">
            <span class="card-title">Name: <%= student.name %></span>
						<p>Email: <%= student.email %></p>
            <p>Course Enrollments: None</p>
          </div>
          <div class="card-action">
            <a href="#">View Profile</a>
          </div>
        </div>
      </div>
    <% end %>
</div>

app/views/students/new.html.erb
<% if @student.errors.any? %>
  <div class="container">
    <div class="row sign-up-form">
      <div class="col s12 m12">
        <div class="card-panel red lighten-2 ">
          <span class="white-text">
            <strong><%= pluralize(@student.errors.count, "error") %></strong>
            prohibited your profile from being created
            <ul>
              <% @student.errors.full_messages.each do |message| %>
                <li><%= message %></li>
              <% end %>
            </ul>
          </span>
        </div>
      </div>
    </div>
  </div>
<% end %>

<div class="container">
  <div class="row center sign-up-form">
    <div class="col s12 m12 l12">
      <div class="card-panel">
        <h3>Sign up!</h3>
        <div class="row">      
          <%= form_for(@student, html: {class: "col s12"}) do |f| %>
            <div class="row">
              <div class="input-field col s12">
                <%= f.text_field :name, placeholder: "Enter yout full name", autofocus: true %>
                <%= f.label :name %>
              </div>
            </div> 
            <div class="row">
              <div class="input-field col s12">
                <%= f.label :email %>
                <%= f.email_field :email %>
              </div>
            </div>
            <div class="row">
              <div class="input-field col s12">
                <%= f.submit "Sign up", class: "btn waves-effect waves-light right" %>
              </div>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/students/show.html.erb
<h3>Current enrollments</h3>
<div class="row sign-up-form">
  <div class="col s6 m6">
    <div class="card blue-grey darken-1">
      <div class="card-content white-text">
        <span class="card-title">Name: <%= @student.name %></span>
        <p>Email: <%= @student.email %></p>
        <p>Course Enrollments: None</p>
      </div>
    </div>
    <%= link_to '<i class="material-icons right">create</i>Edit your profile'.html_safe, edit_student_path(@student), class: "waves-effect waves-light btn" %>
  </div>
</div>